### ISSUE TITLE
gettext, warning  with  Elixir 1.14.0

### ISSUE THREAD

**Issue by cocoaway** [jeramyRR/cosmos_db_ex#13]
**Describe the bug**
Hello, elixir 1.14 generates this warning 

```
warning: the :gettext compiler is no longer required in your mix.exs

```

**To Reproduce**
```
mix deps compile    or  mix compile
```

**Desktop **
 - OS: macOS Catalina
 - Elixir 1.14.0
 - Erlang 25.1
 

** Full output **

```
warning: the :gettext compiler is no longer required in your mix.exs.

Please find the following line in your mix.exs and remove the :gettext entry:

    compilers: [..., :gettext, ...] ++ Mix.compilers(),

  (gettext 0.20.0) lib/mix/tasks/compile.gettext.ex:5: Mix.Tasks.Compile.Gettext.run/1
  (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1
```

**Comment by jeramyRR** [comment]
Rgr, will fix this warning.  Thanks for reporting it.
